---
- name: Install Azure CLI
  hosts: localhost
  become: yes
  tasks:
    - name: Install prerequisites on Debian/Ubuntu
      apt:
        name: [ca-certificates, curl, apt-transport-https, lsb-release, gnupg]
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Microsoft GPG key and repository on Debian/Ubuntu
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main
      when: ansible_os_family == 'Debian'

    - name: Install Azure CLI on Debian/Ubuntu
      apt:
        name: azure-cli
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Azure CLI on RHEL/CentOS
      yum:
        name: azure-cli
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Azure CLI on macOS
      homebrew:
        name: azure-cli
        state: present
      when: ansible_os_family == 'Darwin'
