stages:
  - build
  - test
  - docker_build
  - docker_push

variables:
  BUILD_TYPE: "Release"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Job: Build the project
build:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y libpqxx-dev podman buildah libvtk9-dev python3-vtk9 qtcreator qtbase5-dev qt5-qmake cmake libboost-all-dev libwebsocketpp-dev libssl-dev build-essential xorg-dev libx11-dev libglu1-mesa-dev freeglut3-dev libglew2.2 libglew-dev libglu1-mesa libgl1-mesa-glx libgl1-mesa-dev libglfw3-dev libglfw3 libomp-dev fftw3-dev
  script:
    - ./run.sh
    - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOpenMP_CXX_FLAGS="-fopenmp" -DOpenMP_CXX_LIB_NAMES="gomp"
    - cmake --build build --config $BUILD_TYPE
  artifacts:
    paths:
      - build/
  only:
    - branches
    - merge_requests

# Job: Test the project
test:
  stage: test
  image: ubuntu:latest
  dependencies:
    - build
  script:
    - cd build
    - ctest -C $BUILD_TYPE
  only:
    - branches
    - merge_requests

# Job: Build Docker images
docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
    - echo "$GITLAB_TOKEN" | docker login ghcr.io -u "$GITLAB_USERNAME" --password-stdin
  script:
    - docker build -t ghcr.io/$GITLAB_USERNAME/aarnn:latest --build-arg POSTGRES_USER=$POSTGRES_USER --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD -f Dockerfile .
    - docker build -t ghcr.io/$GITLAB_USERNAME/aarnn-postgres:latest --build-arg POSTGRES_USER=$POSTGRES_USER --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD -f Dockerfile.postgres .
  artifacts:
    paths:
      - docker_images/
  only:
    - main
  needs:
    - build

# Job: Push Docker images
docker_push:
  stage: docker_push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
    - echo "$GITLAB_TOKEN" | docker login ghcr.io -u "$GITLAB_USERNAME" --password-stdin
  script:
    - docker push ghcr.io/$GITLAB_USERNAME/aarnn:latest
    - docker push ghcr.io/$GITLAB_USERNAME/aarnn-postgres:latest
  only:
    - main
  needs:
    - docker_build
