version: '3.8'
services:
  postgres:
    build:
      dockerfile: Dockerfile.postgres
    env_file:
      - ./.env
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2000M
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME : ${POSTGRES_USERNAME}
    networks:
      - my_net

  aarnn:
    build:
      dockerfile: Dockerfile.aarnnFullBuild
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000m
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME : "neurons"
      POSTGRES_USERNAME : ${POSTGRES_USERNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - my_net

networks:
  my_net:
    name: my_net
    external: true

