version: '3.8'
services: 
  aarnn_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    networks:
      - neuro_network

  aarnn_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - neuro_network

networks:
  neuro_network:
    driver: bridge

