services:
  postgres:
    build: 
      dockerfile: Dockerfile.postgres
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 4G 
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD : "GeneTics99!"  
  aarnn:
    build: 
      dockerfile: Dockerfile.aarnn
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 4G 
    volumes:
      - .:/app
    depends_on:
      - postgres  
    environment:
      POSTGRES_PASSWORD : "GeneTics99!"
      POSTGRES_DBNAME : "neurons"
      POSTGRES_USERNAME : "postgres"
      POSTGRES_PORT: 5342
      POSTGRES_URL: "postgres"